from pathlib import Path

P = Path('marketplace_scanner.py')
s = P.read_text(encoding='utf-8')

# Amazon HTTP kartında min/max almak hatalıdır. Ana güncel fiyat ile strike
# fiyatı birbirinden ayrı okuyoruz; kupon/taksit/başka fiyatlar hesaba girmez.
old_http = '''            vals = []\n            for sel in ['.a-price .a-offscreen', '.a-text-price .a-offscreen', '[data-a-strike="true"] .a-offscreen']:\n                for el in card.select(sel):\n                    x = money(el.get_text(' ', strip=True))\n                    if x and x not in vals:\n                        vals.append(x)\n            if len(vals) < 2:\n                vals = _raw_card_prices(card.get_text(' ', strip=True))\n            if len(vals) < 2:\n                continue\n            current, previous = min(vals), max(vals)\n'''
new_http = '''            current_vals = []\n            previous_vals = []\n            for el in card.select('.a-price:not(.a-text-price) .a-offscreen'):\n                x = money(el.get_text(' ', strip=True))\n                if x and x not in current_vals:\n                    current_vals.append(x)\n            for el in card.select('.a-text-price .a-offscreen, [data-a-strike="true"] .a-offscreen'):\n                x = money(el.get_text(' ', strip=True))\n                if x and x not in previous_vals:\n                    previous_vals.append(x)\n            if not current_vals or not previous_vals:\n                continue\n            current = current_vals[0]\n            previous = min((x for x in previous_vals if x > current), default=None)\n            if previous is None:\n                continue\n'''
if old_http in s:
    s = s.replace(old_http, new_http, 1)

# Playwright Amazon fallbackında da min/max kullanılmasını engelle.
old_fallback = '''            vals = prices(card)\n            if len(vals) < 2:\n                vals = _raw_card_prices(card)\n            if len(vals) < 2:\n                continue\n            current, previous = min(vals), max(vals)\n'''
new_fallback = '''            if site == 'Amazon':\n                current_vals = []\n                previous_vals = []\n                for el in page.locator('.a-price:not(.a-text-price) .a-offscreen').all():\n                    try:\n                        x = money(el.inner_text())\n                    except Exception:\n                        x = None\n                    if x and x not in current_vals:\n                        current_vals.append(x)\n                for raw_el in re.findall(r'(?i)(?:<[^>]+class=["\\\'][^"\\\']*a-text-price[^"\\\']*["\\\'][^>]*>.*?</[^>]+>)', card):\n                    x = money(re.sub(r'<[^>]+>', ' ', raw_el))\n                    if x and x not in previous_vals:\n                        previous_vals.append(x)\n                if not current_vals or not previous_vals:\n                    continue\n                current = current_vals[0]\n                previous = min((x for x in previous_vals if x > current), default=None)\n                if previous is None:\n                    continue\n            else:\n                vals = prices(card)\n                if len(vals) < 2:\n                    vals = _raw_card_prices(card)\n                if len(vals) < 2:\n                    continue\n                current, previous = min(vals), max(vals)\n'''
# The runtime scanner's fallback card is text, so use a safer DOM-free Amazon path:
if old_fallback in s:
    replacement = '''            if site == 'Amazon':\n                # Amazon fallback kartında görünen ilk fiyatı güncel, strike fiyatı önceki kabul et.\n                current_m = re.search(r'(?<![0-9])([0-9]{1,3}(?:[.,][0-9]{3})*(?:[.,][0-9]{2})?)\\s*(?:TL|₺)', card, re.I)\n                strike_m = re.search(r'(?i)(?:önce|eski|liste|was|list price)[^0-9]{0,40}([0-9]{1,3}(?:[.,][0-9]{3})*(?:[.,][0-9]{2})?)\\s*(?:TL|₺)', card)\n                if not current_m or not strike_m:\n                    continue\n                current = money(current_m.group(1)); previous = money(strike_m.group(1))\n                if not current or not previous:\n                    continue\n            else:\n                vals = prices(card)\n                if len(vals) < 2:\n                    vals = _raw_card_prices(card)\n                if len(vals) < 2:\n                    continue\n                current, previous = min(vals), max(vals)\n'''
    s = s.replace(old_fallback, replacement, 1)

compile(s, str(P), 'exec')
P.write_text(s, encoding='utf-8')
print('AMAZON PRICE SOURCE GUARD OK | min/max kaldırıldı | ana fiyat/strike ayrıldı')
