create table if not exists price_history (
  id bigint generated by default as identity primary key,
  product_url text not null,
  site text not null,
  price numeric not null,
  observed_at timestamptz not null default now()
);

create index if not exists price_history_product_url_observed_at_idx
on price_history (product_url, observed_at desc);

alter table price_history enable row level security;
